sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1   
after_success:
-docker login -u $DOCKER_USER -p $DOCKER_PASS
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
